// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

public interface ImAckMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImAckMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 fromUserId = 1;</code>
   */
  long getFromUserId();

  /**
   * <code>string messageid = 2;</code>
   */
  java.lang.String getMessageid();
  /**
   * <code>string messageid = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageidBytes();
}
