// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

public interface ImAddFriendMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImAddFriendMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
   */
  boolean hasAddFriendMessageContent();
  /**
   * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
   */
  com.hwl.imcore.improto.ImAddFriendMessageContent getAddFriendMessageContent();
  /**
   * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
   */
  com.hwl.imcore.improto.ImAddFriendMessageContentOrBuilder getAddFriendMessageContentOrBuilder();

  /**
   * <code>uint64 buildTime = 2;</code>
   */
  long getBuildTime();
}
