// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

/**
 * <pre>
 *add friend message
 * </pre>
 *
 * Protobuf type {@code ImAddFriendMessageRequest}
 */
public  final class ImAddFriendMessageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ImAddFriendMessageRequest)
    ImAddFriendMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImAddFriendMessageRequest.newBuilder() to construct.
  private ImAddFriendMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImAddFriendMessageRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ImAddFriendMessageRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.hwl.imcore.improto.ImAddFriendMessageContent.Builder subBuilder = null;
            if (addFriendMessageContent_ != null) {
              subBuilder = addFriendMessageContent_.toBuilder();
            }
            addFriendMessageContent_ = input.readMessage(com.hwl.imcore.improto.ImAddFriendMessageContent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(addFriendMessageContent_);
              addFriendMessageContent_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hwl.imcore.improto.ImMessage.internal_static_ImAddFriendMessageRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hwl.imcore.improto.ImMessage.internal_static_ImAddFriendMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hwl.imcore.improto.ImAddFriendMessageRequest.class, com.hwl.imcore.improto.ImAddFriendMessageRequest.Builder.class);
  }

  public static final int ADDFRIENDMESSAGECONTENT_FIELD_NUMBER = 1;
  private com.hwl.imcore.improto.ImAddFriendMessageContent addFriendMessageContent_;
  /**
   * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
   */
  public boolean hasAddFriendMessageContent() {
    return addFriendMessageContent_ != null;
  }
  /**
   * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
   */
  public com.hwl.imcore.improto.ImAddFriendMessageContent getAddFriendMessageContent() {
    return addFriendMessageContent_ == null ? com.hwl.imcore.improto.ImAddFriendMessageContent.getDefaultInstance() : addFriendMessageContent_;
  }
  /**
   * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
   */
  public com.hwl.imcore.improto.ImAddFriendMessageContentOrBuilder getAddFriendMessageContentOrBuilder() {
    return getAddFriendMessageContent();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (addFriendMessageContent_ != null) {
      output.writeMessage(1, getAddFriendMessageContent());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (addFriendMessageContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAddFriendMessageContent());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hwl.imcore.improto.ImAddFriendMessageRequest)) {
      return super.equals(obj);
    }
    com.hwl.imcore.improto.ImAddFriendMessageRequest other = (com.hwl.imcore.improto.ImAddFriendMessageRequest) obj;

    boolean result = true;
    result = result && (hasAddFriendMessageContent() == other.hasAddFriendMessageContent());
    if (hasAddFriendMessageContent()) {
      result = result && getAddFriendMessageContent()
          .equals(other.getAddFriendMessageContent());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAddFriendMessageContent()) {
      hash = (37 * hash) + ADDFRIENDMESSAGECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getAddFriendMessageContent().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hwl.imcore.improto.ImAddFriendMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hwl.imcore.improto.ImAddFriendMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImAddFriendMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hwl.imcore.improto.ImAddFriendMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImAddFriendMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hwl.imcore.improto.ImAddFriendMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImAddFriendMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hwl.imcore.improto.ImAddFriendMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImAddFriendMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hwl.imcore.improto.ImAddFriendMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImAddFriendMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hwl.imcore.improto.ImAddFriendMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hwl.imcore.improto.ImAddFriendMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *add friend message
   * </pre>
   *
   * Protobuf type {@code ImAddFriendMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ImAddFriendMessageRequest)
      com.hwl.imcore.improto.ImAddFriendMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hwl.imcore.improto.ImMessage.internal_static_ImAddFriendMessageRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hwl.imcore.improto.ImMessage.internal_static_ImAddFriendMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hwl.imcore.improto.ImAddFriendMessageRequest.class, com.hwl.imcore.improto.ImAddFriendMessageRequest.Builder.class);
    }

    // Construct using com.hwl.imcore.improto.ImAddFriendMessageRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (addFriendMessageContentBuilder_ == null) {
        addFriendMessageContent_ = null;
      } else {
        addFriendMessageContent_ = null;
        addFriendMessageContentBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hwl.imcore.improto.ImMessage.internal_static_ImAddFriendMessageRequest_descriptor;
    }

    public com.hwl.imcore.improto.ImAddFriendMessageRequest getDefaultInstanceForType() {
      return com.hwl.imcore.improto.ImAddFriendMessageRequest.getDefaultInstance();
    }

    public com.hwl.imcore.improto.ImAddFriendMessageRequest build() {
      com.hwl.imcore.improto.ImAddFriendMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.hwl.imcore.improto.ImAddFriendMessageRequest buildPartial() {
      com.hwl.imcore.improto.ImAddFriendMessageRequest result = new com.hwl.imcore.improto.ImAddFriendMessageRequest(this);
      if (addFriendMessageContentBuilder_ == null) {
        result.addFriendMessageContent_ = addFriendMessageContent_;
      } else {
        result.addFriendMessageContent_ = addFriendMessageContentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hwl.imcore.improto.ImAddFriendMessageRequest) {
        return mergeFrom((com.hwl.imcore.improto.ImAddFriendMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hwl.imcore.improto.ImAddFriendMessageRequest other) {
      if (other == com.hwl.imcore.improto.ImAddFriendMessageRequest.getDefaultInstance()) return this;
      if (other.hasAddFriendMessageContent()) {
        mergeAddFriendMessageContent(other.getAddFriendMessageContent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hwl.imcore.improto.ImAddFriendMessageRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hwl.imcore.improto.ImAddFriendMessageRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.hwl.imcore.improto.ImAddFriendMessageContent addFriendMessageContent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hwl.imcore.improto.ImAddFriendMessageContent, com.hwl.imcore.improto.ImAddFriendMessageContent.Builder, com.hwl.imcore.improto.ImAddFriendMessageContentOrBuilder> addFriendMessageContentBuilder_;
    /**
     * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
     */
    public boolean hasAddFriendMessageContent() {
      return addFriendMessageContentBuilder_ != null || addFriendMessageContent_ != null;
    }
    /**
     * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
     */
    public com.hwl.imcore.improto.ImAddFriendMessageContent getAddFriendMessageContent() {
      if (addFriendMessageContentBuilder_ == null) {
        return addFriendMessageContent_ == null ? com.hwl.imcore.improto.ImAddFriendMessageContent.getDefaultInstance() : addFriendMessageContent_;
      } else {
        return addFriendMessageContentBuilder_.getMessage();
      }
    }
    /**
     * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
     */
    public Builder setAddFriendMessageContent(com.hwl.imcore.improto.ImAddFriendMessageContent value) {
      if (addFriendMessageContentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        addFriendMessageContent_ = value;
        onChanged();
      } else {
        addFriendMessageContentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
     */
    public Builder setAddFriendMessageContent(
        com.hwl.imcore.improto.ImAddFriendMessageContent.Builder builderForValue) {
      if (addFriendMessageContentBuilder_ == null) {
        addFriendMessageContent_ = builderForValue.build();
        onChanged();
      } else {
        addFriendMessageContentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
     */
    public Builder mergeAddFriendMessageContent(com.hwl.imcore.improto.ImAddFriendMessageContent value) {
      if (addFriendMessageContentBuilder_ == null) {
        if (addFriendMessageContent_ != null) {
          addFriendMessageContent_ =
            com.hwl.imcore.improto.ImAddFriendMessageContent.newBuilder(addFriendMessageContent_).mergeFrom(value).buildPartial();
        } else {
          addFriendMessageContent_ = value;
        }
        onChanged();
      } else {
        addFriendMessageContentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
     */
    public Builder clearAddFriendMessageContent() {
      if (addFriendMessageContentBuilder_ == null) {
        addFriendMessageContent_ = null;
        onChanged();
      } else {
        addFriendMessageContent_ = null;
        addFriendMessageContentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
     */
    public com.hwl.imcore.improto.ImAddFriendMessageContent.Builder getAddFriendMessageContentBuilder() {
      
      onChanged();
      return getAddFriendMessageContentFieldBuilder().getBuilder();
    }
    /**
     * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
     */
    public com.hwl.imcore.improto.ImAddFriendMessageContentOrBuilder getAddFriendMessageContentOrBuilder() {
      if (addFriendMessageContentBuilder_ != null) {
        return addFriendMessageContentBuilder_.getMessageOrBuilder();
      } else {
        return addFriendMessageContent_ == null ?
            com.hwl.imcore.improto.ImAddFriendMessageContent.getDefaultInstance() : addFriendMessageContent_;
      }
    }
    /**
     * <code>.ImAddFriendMessageContent addFriendMessageContent = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hwl.imcore.improto.ImAddFriendMessageContent, com.hwl.imcore.improto.ImAddFriendMessageContent.Builder, com.hwl.imcore.improto.ImAddFriendMessageContentOrBuilder> 
        getAddFriendMessageContentFieldBuilder() {
      if (addFriendMessageContentBuilder_ == null) {
        addFriendMessageContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hwl.imcore.improto.ImAddFriendMessageContent, com.hwl.imcore.improto.ImAddFriendMessageContent.Builder, com.hwl.imcore.improto.ImAddFriendMessageContentOrBuilder>(
                getAddFriendMessageContent(),
                getParentForChildren(),
                isClean());
        addFriendMessageContent_ = null;
      }
      return addFriendMessageContentBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ImAddFriendMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:ImAddFriendMessageRequest)
  private static final com.hwl.imcore.improto.ImAddFriendMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hwl.imcore.improto.ImAddFriendMessageRequest();
  }

  public static com.hwl.imcore.improto.ImAddFriendMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ImAddFriendMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<ImAddFriendMessageRequest>() {
    public ImAddFriendMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ImAddFriendMessageRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ImAddFriendMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImAddFriendMessageRequest> getParserForType() {
    return PARSER;
  }

  public com.hwl.imcore.improto.ImAddFriendMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

