// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

public interface ImAddFriendRequestMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImAddFriendRequestMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 fromUserId = 1;</code>
   */
  long getFromUserId();

  /**
   * <code>string fromUserName = 2;</code>
   */
  java.lang.String getFromUserName();
  /**
   * <code>string fromUserName = 2;</code>
   */
  com.google.protobuf.ByteString
      getFromUserNameBytes();

  /**
   * <code>string fromUserHeadImage = 3;</code>
   */
  java.lang.String getFromUserHeadImage();
  /**
   * <code>string fromUserHeadImage = 3;</code>
   */
  com.google.protobuf.ByteString
      getFromUserHeadImageBytes();

  /**
   * <code>uint64 toUserId = 4;</code>
   */
  long getToUserId();

  /**
   * <code>string toUserName = 5;</code>
   */
  java.lang.String getToUserName();
  /**
   * <code>string toUserName = 5;</code>
   */
  com.google.protobuf.ByteString
      getToUserNameBytes();
}
