// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

/**
 * Protobuf type {@code ImChatUserMessageResponse}
 */
public  final class ImChatUserMessageResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ImChatUserMessageResponse)
    ImChatUserMessageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImChatUserMessageResponse.newBuilder() to construct.
  private ImChatUserMessageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImChatUserMessageResponse() {
    buildTime_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ImChatUserMessageResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.hwl.imcore.improto.ImChatUserMessageContent.Builder subBuilder = null;
            if (chatUserMessageContent_ != null) {
              subBuilder = chatUserMessageContent_.toBuilder();
            }
            chatUserMessageContent_ = input.readMessage(com.hwl.imcore.improto.ImChatUserMessageContent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(chatUserMessageContent_);
              chatUserMessageContent_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            buildTime_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hwl.imcore.improto.ImMessage.internal_static_ImChatUserMessageResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hwl.imcore.improto.ImMessage.internal_static_ImChatUserMessageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hwl.imcore.improto.ImChatUserMessageResponse.class, com.hwl.imcore.improto.ImChatUserMessageResponse.Builder.class);
  }

  public static final int CHATUSERMESSAGECONTENT_FIELD_NUMBER = 1;
  private com.hwl.imcore.improto.ImChatUserMessageContent chatUserMessageContent_;
  /**
   * <code>.ImChatUserMessageContent chatUserMessageContent = 1;</code>
   */
  public boolean hasChatUserMessageContent() {
    return chatUserMessageContent_ != null;
  }
  /**
   * <code>.ImChatUserMessageContent chatUserMessageContent = 1;</code>
   */
  public com.hwl.imcore.improto.ImChatUserMessageContent getChatUserMessageContent() {
    return chatUserMessageContent_ == null ? com.hwl.imcore.improto.ImChatUserMessageContent.getDefaultInstance() : chatUserMessageContent_;
  }
  /**
   * <code>.ImChatUserMessageContent chatUserMessageContent = 1;</code>
   */
  public com.hwl.imcore.improto.ImChatUserMessageContentOrBuilder getChatUserMessageContentOrBuilder() {
    return getChatUserMessageContent();
  }

  public static final int BUILDTIME_FIELD_NUMBER = 2;
  private long buildTime_;
  /**
   * <code>uint64 buildTime = 2;</code>
   */
  public long getBuildTime() {
    return buildTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (chatUserMessageContent_ != null) {
      output.writeMessage(1, getChatUserMessageContent());
    }
    if (buildTime_ != 0L) {
      output.writeUInt64(2, buildTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (chatUserMessageContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getChatUserMessageContent());
    }
    if (buildTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, buildTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hwl.imcore.improto.ImChatUserMessageResponse)) {
      return super.equals(obj);
    }
    com.hwl.imcore.improto.ImChatUserMessageResponse other = (com.hwl.imcore.improto.ImChatUserMessageResponse) obj;

    boolean result = true;
    result = result && (hasChatUserMessageContent() == other.hasChatUserMessageContent());
    if (hasChatUserMessageContent()) {
      result = result && getChatUserMessageContent()
          .equals(other.getChatUserMessageContent());
    }
    result = result && (getBuildTime()
        == other.getBuildTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasChatUserMessageContent()) {
      hash = (37 * hash) + CHATUSERMESSAGECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getChatUserMessageContent().hashCode();
    }
    hash = (37 * hash) + BUILDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBuildTime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hwl.imcore.improto.ImChatUserMessageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hwl.imcore.improto.ImChatUserMessageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImChatUserMessageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hwl.imcore.improto.ImChatUserMessageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImChatUserMessageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hwl.imcore.improto.ImChatUserMessageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImChatUserMessageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hwl.imcore.improto.ImChatUserMessageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImChatUserMessageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hwl.imcore.improto.ImChatUserMessageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImChatUserMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hwl.imcore.improto.ImChatUserMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hwl.imcore.improto.ImChatUserMessageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ImChatUserMessageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ImChatUserMessageResponse)
      com.hwl.imcore.improto.ImChatUserMessageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hwl.imcore.improto.ImMessage.internal_static_ImChatUserMessageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hwl.imcore.improto.ImMessage.internal_static_ImChatUserMessageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hwl.imcore.improto.ImChatUserMessageResponse.class, com.hwl.imcore.improto.ImChatUserMessageResponse.Builder.class);
    }

    // Construct using com.hwl.imcore.improto.ImChatUserMessageResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (chatUserMessageContentBuilder_ == null) {
        chatUserMessageContent_ = null;
      } else {
        chatUserMessageContent_ = null;
        chatUserMessageContentBuilder_ = null;
      }
      buildTime_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hwl.imcore.improto.ImMessage.internal_static_ImChatUserMessageResponse_descriptor;
    }

    @java.lang.Override
    public com.hwl.imcore.improto.ImChatUserMessageResponse getDefaultInstanceForType() {
      return com.hwl.imcore.improto.ImChatUserMessageResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.hwl.imcore.improto.ImChatUserMessageResponse build() {
      com.hwl.imcore.improto.ImChatUserMessageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hwl.imcore.improto.ImChatUserMessageResponse buildPartial() {
      com.hwl.imcore.improto.ImChatUserMessageResponse result = new com.hwl.imcore.improto.ImChatUserMessageResponse(this);
      if (chatUserMessageContentBuilder_ == null) {
        result.chatUserMessageContent_ = chatUserMessageContent_;
      } else {
        result.chatUserMessageContent_ = chatUserMessageContentBuilder_.build();
      }
      result.buildTime_ = buildTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hwl.imcore.improto.ImChatUserMessageResponse) {
        return mergeFrom((com.hwl.imcore.improto.ImChatUserMessageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hwl.imcore.improto.ImChatUserMessageResponse other) {
      if (other == com.hwl.imcore.improto.ImChatUserMessageResponse.getDefaultInstance()) return this;
      if (other.hasChatUserMessageContent()) {
        mergeChatUserMessageContent(other.getChatUserMessageContent());
      }
      if (other.getBuildTime() != 0L) {
        setBuildTime(other.getBuildTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hwl.imcore.improto.ImChatUserMessageResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hwl.imcore.improto.ImChatUserMessageResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.hwl.imcore.improto.ImChatUserMessageContent chatUserMessageContent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hwl.imcore.improto.ImChatUserMessageContent, com.hwl.imcore.improto.ImChatUserMessageContent.Builder, com.hwl.imcore.improto.ImChatUserMessageContentOrBuilder> chatUserMessageContentBuilder_;
    /**
     * <code>.ImChatUserMessageContent chatUserMessageContent = 1;</code>
     */
    public boolean hasChatUserMessageContent() {
      return chatUserMessageContentBuilder_ != null || chatUserMessageContent_ != null;
    }
    /**
     * <code>.ImChatUserMessageContent chatUserMessageContent = 1;</code>
     */
    public com.hwl.imcore.improto.ImChatUserMessageContent getChatUserMessageContent() {
      if (chatUserMessageContentBuilder_ == null) {
        return chatUserMessageContent_ == null ? com.hwl.imcore.improto.ImChatUserMessageContent.getDefaultInstance() : chatUserMessageContent_;
      } else {
        return chatUserMessageContentBuilder_.getMessage();
      }
    }
    /**
     * <code>.ImChatUserMessageContent chatUserMessageContent = 1;</code>
     */
    public Builder setChatUserMessageContent(com.hwl.imcore.improto.ImChatUserMessageContent value) {
      if (chatUserMessageContentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chatUserMessageContent_ = value;
        onChanged();
      } else {
        chatUserMessageContentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ImChatUserMessageContent chatUserMessageContent = 1;</code>
     */
    public Builder setChatUserMessageContent(
        com.hwl.imcore.improto.ImChatUserMessageContent.Builder builderForValue) {
      if (chatUserMessageContentBuilder_ == null) {
        chatUserMessageContent_ = builderForValue.build();
        onChanged();
      } else {
        chatUserMessageContentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ImChatUserMessageContent chatUserMessageContent = 1;</code>
     */
    public Builder mergeChatUserMessageContent(com.hwl.imcore.improto.ImChatUserMessageContent value) {
      if (chatUserMessageContentBuilder_ == null) {
        if (chatUserMessageContent_ != null) {
          chatUserMessageContent_ =
            com.hwl.imcore.improto.ImChatUserMessageContent.newBuilder(chatUserMessageContent_).mergeFrom(value).buildPartial();
        } else {
          chatUserMessageContent_ = value;
        }
        onChanged();
      } else {
        chatUserMessageContentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ImChatUserMessageContent chatUserMessageContent = 1;</code>
     */
    public Builder clearChatUserMessageContent() {
      if (chatUserMessageContentBuilder_ == null) {
        chatUserMessageContent_ = null;
        onChanged();
      } else {
        chatUserMessageContent_ = null;
        chatUserMessageContentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ImChatUserMessageContent chatUserMessageContent = 1;</code>
     */
    public com.hwl.imcore.improto.ImChatUserMessageContent.Builder getChatUserMessageContentBuilder() {
      
      onChanged();
      return getChatUserMessageContentFieldBuilder().getBuilder();
    }
    /**
     * <code>.ImChatUserMessageContent chatUserMessageContent = 1;</code>
     */
    public com.hwl.imcore.improto.ImChatUserMessageContentOrBuilder getChatUserMessageContentOrBuilder() {
      if (chatUserMessageContentBuilder_ != null) {
        return chatUserMessageContentBuilder_.getMessageOrBuilder();
      } else {
        return chatUserMessageContent_ == null ?
            com.hwl.imcore.improto.ImChatUserMessageContent.getDefaultInstance() : chatUserMessageContent_;
      }
    }
    /**
     * <code>.ImChatUserMessageContent chatUserMessageContent = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.hwl.imcore.improto.ImChatUserMessageContent, com.hwl.imcore.improto.ImChatUserMessageContent.Builder, com.hwl.imcore.improto.ImChatUserMessageContentOrBuilder> 
        getChatUserMessageContentFieldBuilder() {
      if (chatUserMessageContentBuilder_ == null) {
        chatUserMessageContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.hwl.imcore.improto.ImChatUserMessageContent, com.hwl.imcore.improto.ImChatUserMessageContent.Builder, com.hwl.imcore.improto.ImChatUserMessageContentOrBuilder>(
                getChatUserMessageContent(),
                getParentForChildren(),
                isClean());
        chatUserMessageContent_ = null;
      }
      return chatUserMessageContentBuilder_;
    }

    private long buildTime_ ;
    /**
     * <code>uint64 buildTime = 2;</code>
     */
    public long getBuildTime() {
      return buildTime_;
    }
    /**
     * <code>uint64 buildTime = 2;</code>
     */
    public Builder setBuildTime(long value) {
      
      buildTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 buildTime = 2;</code>
     */
    public Builder clearBuildTime() {
      
      buildTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ImChatUserMessageResponse)
  }

  // @@protoc_insertion_point(class_scope:ImChatUserMessageResponse)
  private static final com.hwl.imcore.improto.ImChatUserMessageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hwl.imcore.improto.ImChatUserMessageResponse();
  }

  public static com.hwl.imcore.improto.ImChatUserMessageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ImChatUserMessageResponse>
      PARSER = new com.google.protobuf.AbstractParser<ImChatUserMessageResponse>() {
    @java.lang.Override
    public ImChatUserMessageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ImChatUserMessageResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ImChatUserMessageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImChatUserMessageResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hwl.imcore.improto.ImChatUserMessageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

