// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

/**
 * Protobuf type {@code ImChatSettingMessageContent}
 */
public  final class ImChatSettingMessageContent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ImChatSettingMessageContent)
    ImChatSettingMessageContentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImChatSettingMessageContent.newBuilder() to construct.
  private ImChatSettingMessageContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImChatSettingMessageContent() {
    settingType_ = 0;
    groupNote_ = "";
    groupName_ = "";
    userRemark_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ImChatSettingMessageContent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            settingType_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            groupNote_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            groupName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            userRemark_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hwl.imcore.improto.ImMessage.internal_static_ImChatSettingMessageContent_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hwl.imcore.improto.ImMessage.internal_static_ImChatSettingMessageContent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hwl.imcore.improto.ImChatSettingMessageContent.class, com.hwl.imcore.improto.ImChatSettingMessageContent.Builder.class);
  }

  public static final int SETTINGTYPE_FIELD_NUMBER = 1;
  private int settingType_;
  /**
   * <code>.ImChatSettingType settingType = 1;</code>
   */
  public int getSettingTypeValue() {
    return settingType_;
  }
  /**
   * <code>.ImChatSettingType settingType = 1;</code>
   */
  public com.hwl.imcore.improto.ImChatSettingType getSettingType() {
    com.hwl.imcore.improto.ImChatSettingType result = com.hwl.imcore.improto.ImChatSettingType.valueOf(settingType_);
    return result == null ? com.hwl.imcore.improto.ImChatSettingType.UNRECOGNIZED : result;
  }

  public static final int GROUPNOTE_FIELD_NUMBER = 2;
  private volatile java.lang.Object groupNote_;
  /**
   * <code>string groupNote = 2;</code>
   */
  public java.lang.String getGroupNote() {
    java.lang.Object ref = groupNote_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupNote_ = s;
      return s;
    }
  }
  /**
   * <code>string groupNote = 2;</code>
   */
  public com.google.protobuf.ByteString
      getGroupNoteBytes() {
    java.lang.Object ref = groupNote_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupNote_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUPNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object groupName_;
  /**
   * <code>string groupName = 3;</code>
   */
  public java.lang.String getGroupName() {
    java.lang.Object ref = groupName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      groupName_ = s;
      return s;
    }
  }
  /**
   * <code>string groupName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getGroupNameBytes() {
    java.lang.Object ref = groupName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      groupName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERREMARK_FIELD_NUMBER = 4;
  private volatile java.lang.Object userRemark_;
  /**
   * <code>string userRemark = 4;</code>
   */
  public java.lang.String getUserRemark() {
    java.lang.Object ref = userRemark_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userRemark_ = s;
      return s;
    }
  }
  /**
   * <code>string userRemark = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUserRemarkBytes() {
    java.lang.Object ref = userRemark_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userRemark_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (settingType_ != com.hwl.imcore.improto.ImChatSettingType.SettingNone.getNumber()) {
      output.writeEnum(1, settingType_);
    }
    if (!getGroupNoteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, groupNote_);
    }
    if (!getGroupNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, groupName_);
    }
    if (!getUserRemarkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userRemark_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (settingType_ != com.hwl.imcore.improto.ImChatSettingType.SettingNone.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, settingType_);
    }
    if (!getGroupNoteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, groupNote_);
    }
    if (!getGroupNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, groupName_);
    }
    if (!getUserRemarkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userRemark_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hwl.imcore.improto.ImChatSettingMessageContent)) {
      return super.equals(obj);
    }
    com.hwl.imcore.improto.ImChatSettingMessageContent other = (com.hwl.imcore.improto.ImChatSettingMessageContent) obj;

    boolean result = true;
    result = result && settingType_ == other.settingType_;
    result = result && getGroupNote()
        .equals(other.getGroupNote());
    result = result && getGroupName()
        .equals(other.getGroupName());
    result = result && getUserRemark()
        .equals(other.getUserRemark());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SETTINGTYPE_FIELD_NUMBER;
    hash = (53 * hash) + settingType_;
    hash = (37 * hash) + GROUPNOTE_FIELD_NUMBER;
    hash = (53 * hash) + getGroupNote().hashCode();
    hash = (37 * hash) + GROUPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getGroupName().hashCode();
    hash = (37 * hash) + USERREMARK_FIELD_NUMBER;
    hash = (53 * hash) + getUserRemark().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hwl.imcore.improto.ImChatSettingMessageContent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hwl.imcore.improto.ImChatSettingMessageContent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImChatSettingMessageContent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hwl.imcore.improto.ImChatSettingMessageContent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImChatSettingMessageContent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hwl.imcore.improto.ImChatSettingMessageContent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImChatSettingMessageContent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hwl.imcore.improto.ImChatSettingMessageContent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImChatSettingMessageContent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hwl.imcore.improto.ImChatSettingMessageContent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hwl.imcore.improto.ImChatSettingMessageContent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hwl.imcore.improto.ImChatSettingMessageContent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hwl.imcore.improto.ImChatSettingMessageContent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ImChatSettingMessageContent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ImChatSettingMessageContent)
      com.hwl.imcore.improto.ImChatSettingMessageContentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hwl.imcore.improto.ImMessage.internal_static_ImChatSettingMessageContent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hwl.imcore.improto.ImMessage.internal_static_ImChatSettingMessageContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hwl.imcore.improto.ImChatSettingMessageContent.class, com.hwl.imcore.improto.ImChatSettingMessageContent.Builder.class);
    }

    // Construct using com.hwl.imcore.improto.ImChatSettingMessageContent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      settingType_ = 0;

      groupNote_ = "";

      groupName_ = "";

      userRemark_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hwl.imcore.improto.ImMessage.internal_static_ImChatSettingMessageContent_descriptor;
    }

    public com.hwl.imcore.improto.ImChatSettingMessageContent getDefaultInstanceForType() {
      return com.hwl.imcore.improto.ImChatSettingMessageContent.getDefaultInstance();
    }

    public com.hwl.imcore.improto.ImChatSettingMessageContent build() {
      com.hwl.imcore.improto.ImChatSettingMessageContent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.hwl.imcore.improto.ImChatSettingMessageContent buildPartial() {
      com.hwl.imcore.improto.ImChatSettingMessageContent result = new com.hwl.imcore.improto.ImChatSettingMessageContent(this);
      result.settingType_ = settingType_;
      result.groupNote_ = groupNote_;
      result.groupName_ = groupName_;
      result.userRemark_ = userRemark_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hwl.imcore.improto.ImChatSettingMessageContent) {
        return mergeFrom((com.hwl.imcore.improto.ImChatSettingMessageContent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hwl.imcore.improto.ImChatSettingMessageContent other) {
      if (other == com.hwl.imcore.improto.ImChatSettingMessageContent.getDefaultInstance()) return this;
      if (other.settingType_ != 0) {
        setSettingTypeValue(other.getSettingTypeValue());
      }
      if (!other.getGroupNote().isEmpty()) {
        groupNote_ = other.groupNote_;
        onChanged();
      }
      if (!other.getGroupName().isEmpty()) {
        groupName_ = other.groupName_;
        onChanged();
      }
      if (!other.getUserRemark().isEmpty()) {
        userRemark_ = other.userRemark_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hwl.imcore.improto.ImChatSettingMessageContent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hwl.imcore.improto.ImChatSettingMessageContent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int settingType_ = 0;
    /**
     * <code>.ImChatSettingType settingType = 1;</code>
     */
    public int getSettingTypeValue() {
      return settingType_;
    }
    /**
     * <code>.ImChatSettingType settingType = 1;</code>
     */
    public Builder setSettingTypeValue(int value) {
      settingType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ImChatSettingType settingType = 1;</code>
     */
    public com.hwl.imcore.improto.ImChatSettingType getSettingType() {
      com.hwl.imcore.improto.ImChatSettingType result = com.hwl.imcore.improto.ImChatSettingType.valueOf(settingType_);
      return result == null ? com.hwl.imcore.improto.ImChatSettingType.UNRECOGNIZED : result;
    }
    /**
     * <code>.ImChatSettingType settingType = 1;</code>
     */
    public Builder setSettingType(com.hwl.imcore.improto.ImChatSettingType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      settingType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ImChatSettingType settingType = 1;</code>
     */
    public Builder clearSettingType() {
      
      settingType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object groupNote_ = "";
    /**
     * <code>string groupNote = 2;</code>
     */
    public java.lang.String getGroupNote() {
      java.lang.Object ref = groupNote_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupNote_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string groupNote = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGroupNoteBytes() {
      java.lang.Object ref = groupNote_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupNote_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string groupNote = 2;</code>
     */
    public Builder setGroupNote(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      groupNote_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string groupNote = 2;</code>
     */
    public Builder clearGroupNote() {
      
      groupNote_ = getDefaultInstance().getGroupNote();
      onChanged();
      return this;
    }
    /**
     * <code>string groupNote = 2;</code>
     */
    public Builder setGroupNoteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      groupNote_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object groupName_ = "";
    /**
     * <code>string groupName = 3;</code>
     */
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string groupName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string groupName = 3;</code>
     */
    public Builder setGroupName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      groupName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string groupName = 3;</code>
     */
    public Builder clearGroupName() {
      
      groupName_ = getDefaultInstance().getGroupName();
      onChanged();
      return this;
    }
    /**
     * <code>string groupName = 3;</code>
     */
    public Builder setGroupNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      groupName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userRemark_ = "";
    /**
     * <code>string userRemark = 4;</code>
     */
    public java.lang.String getUserRemark() {
      java.lang.Object ref = userRemark_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userRemark_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string userRemark = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserRemarkBytes() {
      java.lang.Object ref = userRemark_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userRemark_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userRemark = 4;</code>
     */
    public Builder setUserRemark(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userRemark_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userRemark = 4;</code>
     */
    public Builder clearUserRemark() {
      
      userRemark_ = getDefaultInstance().getUserRemark();
      onChanged();
      return this;
    }
    /**
     * <code>string userRemark = 4;</code>
     */
    public Builder setUserRemarkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userRemark_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ImChatSettingMessageContent)
  }

  // @@protoc_insertion_point(class_scope:ImChatSettingMessageContent)
  private static final com.hwl.imcore.improto.ImChatSettingMessageContent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hwl.imcore.improto.ImChatSettingMessageContent();
  }

  public static com.hwl.imcore.improto.ImChatSettingMessageContent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ImChatSettingMessageContent>
      PARSER = new com.google.protobuf.AbstractParser<ImChatSettingMessageContent>() {
    public ImChatSettingMessageContent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ImChatSettingMessageContent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ImChatSettingMessageContent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImChatSettingMessageContent> getParserForType() {
    return PARSER;
  }

  public com.hwl.imcore.improto.ImChatSettingMessageContent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

