// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

public interface ImChatSettingMessageContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImChatSettingMessageContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ImChatSettingType settingType = 1;</code>
   */
  int getSettingTypeValue();
  /**
   * <code>.ImChatSettingType settingType = 1;</code>
   */
  com.hwl.imcore.improto.ImChatSettingType getSettingType();

  /**
   * <code>.ImUserContent settingUser = 2;</code>
   */
  boolean hasSettingUser();
  /**
   * <code>.ImUserContent settingUser = 2;</code>
   */
  com.hwl.imcore.improto.ImUserContent getSettingUser();
  /**
   * <code>.ImUserContent settingUser = 2;</code>
   */
  com.hwl.imcore.improto.ImUserContentOrBuilder getSettingUserOrBuilder();

  /**
   * <code>string groupGuid = 3;</code>
   */
  java.lang.String getGroupGuid();
  /**
   * <code>string groupGuid = 3;</code>
   */
  com.google.protobuf.ByteString
      getGroupGuidBytes();

  /**
   * <code>string groupNote = 4;</code>
   */
  java.lang.String getGroupNote();
  /**
   * <code>string groupNote = 4;</code>
   */
  com.google.protobuf.ByteString
      getGroupNoteBytes();

  /**
   * <code>string groupName = 5;</code>
   */
  java.lang.String getGroupName();
  /**
   * <code>string groupName = 5;</code>
   */
  com.google.protobuf.ByteString
      getGroupNameBytes();
}
