// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

/**
 * Protobuf enum {@code ImChatSettingType}
 */
public enum ImChatSettingType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SettingNone = 0;</code>
   */
  SettingNone(0),
  /**
   * <code>GroupNote = 1;</code>
   */
  GroupNote(1),
  /**
   * <code>GroupName = 2;</code>
   */
  GroupName(2),
  /**
   * <code>UserRemark = 3;</code>
   */
  UserRemark(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SettingNone = 0;</code>
   */
  public static final int SettingNone_VALUE = 0;
  /**
   * <code>GroupNote = 1;</code>
   */
  public static final int GroupNote_VALUE = 1;
  /**
   * <code>GroupName = 2;</code>
   */
  public static final int GroupName_VALUE = 2;
  /**
   * <code>UserRemark = 3;</code>
   */
  public static final int UserRemark_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ImChatSettingType valueOf(int value) {
    return forNumber(value);
  }

  public static ImChatSettingType forNumber(int value) {
    switch (value) {
      case 0: return SettingNone;
      case 1: return GroupNote;
      case 2: return GroupName;
      case 3: return UserRemark;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ImChatSettingType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ImChatSettingType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ImChatSettingType>() {
          public ImChatSettingType findValueByNumber(int number) {
            return ImChatSettingType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.hwl.imcore.improto.ImMessage.getDescriptor().getEnumTypes().get(3);
  }

  private static final ImChatSettingType[] VALUES = values();

  public static ImChatSettingType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ImChatSettingType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ImChatSettingType)
}

