// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

public interface ImGroupOperateMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImGroupOperateMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ImGroupOperateMessageContent groupOperateMessageContent = 1;</code>
   */
  boolean hasGroupOperateMessageContent();
  /**
   * <code>.ImGroupOperateMessageContent groupOperateMessageContent = 1;</code>
   */
  com.hwl.imcore.improto.ImGroupOperateMessageContent getGroupOperateMessageContent();
  /**
   * <code>.ImGroupOperateMessageContent groupOperateMessageContent = 1;</code>
   */
  com.hwl.imcore.improto.ImGroupOperateMessageContentOrBuilder getGroupOperateMessageContentOrBuilder();
}
