// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

public interface ImHeartBeatMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImHeartBeatMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 currentTime = 1;</code>
   */
  long getCurrentTime();
}
