// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

public final class ImMessage {
  private ImMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImMessageContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImMessageContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImMessageRequestHead_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImMessageRequestHead_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImMessageResponseHead_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImMessageResponseHead_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImUserValidateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImUserValidateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImUserValidateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImUserValidateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImChatUserMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImChatUserMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImChatUserMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImChatUserMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImChatUserMessageContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImChatUserMessageContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImChatGroupMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImChatGroupMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImChatGroupMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImChatGroupMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImChatGroupMessageContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImChatGroupMessageContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImHeartBeatMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImHeartBeatMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImAddFriendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImAddFriendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImAddFriendMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImAddFriendMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImAddFriendMessageContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImAddFriendMessageContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImTestConnectionMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImTestConnectionMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImTestConnectionMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImTestConnectionMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImAckMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImAckMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImChatSettingMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImChatSettingMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImChatSettingMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImChatSettingMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImChatSettingMessageContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImChatSettingMessageContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImGroupOperateMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImGroupOperateMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImGroupOperateMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImGroupOperateMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImGroupOperateMessageContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImGroupOperateMessageContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImUserContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImUserContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImNearCircleOperateMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImNearCircleOperateMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImNearCircleOperateMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImNearCircleOperateMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImNearCircleOperateMessageContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImNearCircleOperateMessageContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImCircleOperateMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImCircleOperateMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImCircleOperateMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImCircleOperateMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImCircleOperateMessageContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImCircleOperateMessageContent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6src/main/java/com/hwl/imcore/protocol/" +
      "im_message.proto\"\206\001\n\020ImMessageContext\022\034\n" +
      "\004type\030\001 \001(\0162\016.ImMessageType\022$\n\007request\030\002" +
      " \001(\0132\021.ImMessageRequestH\000\022&\n\010response\030\003 " +
      "\001(\0132\022.ImMessageResponseH\000B\006\n\004body\"\230\006\n\020Im" +
      "MessageRequest\022*\n\013requestHead\030\001 \001(\0132\025.Im" +
      "MessageRequestHead\0225\n\023userValidateReques" +
      "t\030\002 \001(\0132\026.ImUserValidateRequestH\000\022;\n\026cha" +
      "tUserMessageRequest\030\003 \001(\0132\031.ImChatUserMe" +
      "ssageRequestH\000\022=\n\027chatGroupMessageReques" +
      "t\030\004 \001(\0132\032.ImChatGroupMessageRequestH\000\022=\n" +
      "\027heartBeatMessageRequest\030\005 \001(\0132\032.ImHeart" +
      "BeatMessageRequestH\000\022=\n\027addFriendMessage" +
      "Request\030\006 \001(\0132\032.ImAddFriendMessageReques" +
      "tH\000\022G\n\034testConnectionMessageRequest\030\007 \001(" +
      "\0132\037.ImTestConnectionMessageRequestH\000\0221\n\021" +
      "ackMessageRequest\030\010 \001(\0132\024.ImAckMessageRe" +
      "questH\000\022A\n\031chatSettingMessageRequest\030\t \001" +
      "(\0132\034.ImChatSettingMessageRequestH\000\022C\n\032gr" +
      "oupOperateMessageRequest\030\n \001(\0132\035.ImGroup" +
      "OperateMessageRequestH\000\022M\n\037nearCircleOpe" +
      "rateMessageRequest\030\013 \001(\0132\".ImNearCircleO" +
      "perateMessageRequestH\000\022E\n\033circleOperateM" +
      "essageRequest\030\014 \001(\0132\036.ImCircleOperateMes" +
      "sageRequestH\000B\r\n\013requestBody\"o\n\024ImMessag" +
      "eRequestHead\022\021\n\ttimestamp\030\001 \001(\004\022\016\n\006clien" +
      "t\030\002 \001(\t\022\021\n\tsessionid\030\003 \001(\t\022\020\n\010language\030\004" +
      " \001(\t\022\017\n\007version\030\005 \001(\t\"\274\005\n\021ImMessageRespo" +
      "nse\022,\n\014responseHead\030\001 \001(\0132\026.ImMessageRes" +
      "ponseHead\0227\n\024userValidateResponse\030\002 \001(\0132" +
      "\027.ImUserValidateResponseH\000\022=\n\027chatUserMe" +
      "ssageResponse\030\003 \001(\0132\032.ImChatUserMessageR" +
      "esponseH\000\022?\n\030chatGroupMessageResponse\030\004 " +
      "\001(\0132\033.ImChatGroupMessageResponseH\000\022?\n\030ad" +
      "dFriendMessageResponse\030\005 \001(\0132\033.ImAddFrie" +
      "ndMessageResponseH\000\022I\n\035testConnectionMes" +
      "sageResponse\030\006 \001(\0132 .ImTestConnectionMes" +
      "sageResponseH\000\022C\n\032chatSettingMessageResp" +
      "onse\030\007 \001(\0132\035.ImChatSettingMessageRespons" +
      "eH\000\022E\n\033groupOperateMessageResponse\030\010 \001(\013" +
      "2\036.ImGroupOperateMessageResponseH\000\022O\n ne" +
      "arCircleOperateMessageResponse\030\t \001(\0132#.I" +
      "mNearCircleOperateMessageResponseH\000\022G\n\034c" +
      "ircleOperateMessageResponse\030\n \001(\0132\037.ImCi" +
      "rcleOperateMessageResponseH\000B\016\n\014response" +
      "Body\"\202\001\n\025ImMessageResponseHead\022\014\n\004code\030\001" +
      " \001(\r\022\017\n\007message\030\002 \001(\t\022\r\n\005isack\030\003 \001(\010\022\021\n\t" +
      "messageid\030\004 \001(\t\022(\n\006source\030\005 \001(\0162\030.ImMess" +
      "ageSourcePosition\"I\n\025ImUserValidateReque" +
      "st\022\016\n\006userId\030\001 \001(\004\022\r\n\005token\030\002 \001(\t\022\021\n\tmes" +
      "sageid\030\003 \001(\t\"a\n\026ImUserValidateResponse\022\021" +
      "\n\tisSuccess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022\020\n\010is" +
      "Online\030\003 \001(\010\022\021\n\tsessionid\030\004 \001(\t\"U\n\030ImCha" +
      "tUserMessageRequest\0229\n\026chatUserMessageCo" +
      "ntent\030\001 \001(\0132\031.ImChatUserMessageContent\"i" +
      "\n\031ImChatUserMessageResponse\0229\n\026chatUserM" +
      "essageContent\030\001 \001(\0132\031.ImChatUserMessageC" +
      "ontent\022\021\n\tbuildTime\030\002 \001(\004\"\227\002\n\030ImChatUser" +
      "MessageContent\022\022\n\nfromUserId\030\001 \001(\004\022\024\n\014fr" +
      "omUserName\030\002 \001(\t\022\025\n\rfromUserImage\030\003 \001(\t\022" +
      "\020\n\010toUserId\030\004 \001(\004\022\023\n\013contentType\030\005 \001(\r\022\017" +
      "\n\007content\030\006 \001(\t\022\023\n\013originalUrl\030\007 \001(\t\022\022\n\n" +
      "previewUrl\030\010 \001(\t\022\022\n\nimageWidth\030\t \001(\r\022\023\n\013" +
      "imageHeight\030\n \001(\r\022\014\n\004size\030\013 \001(\r\022\020\n\010playT" +
      "ime\030\014 \001(\r\022\020\n\010isFriend\030\r \001(\010\"X\n\031ImChatGro" +
      "upMessageRequest\022;\n\027chatGroupMessageCont" +
      "ent\030\001 \001(\0132\032.ImChatGroupMessageContent\"l\n" +
      "\032ImChatGroupMessageResponse\022;\n\027chatGroup" +
      "MessageContent\030\001 \001(\0132\032.ImChatGroupMessag" +
      "eContent\022\021\n\tbuildTime\030\002 \001(\004\"\233\002\n\031ImChatGr" +
      "oupMessageContent\022\022\n\nfromUserId\030\001 \001(\004\022\024\n" +
      "\014fromUserName\030\002 \001(\t\022\025\n\rfromUserImage\030\003 \001" +
      "(\t\022\023\n\013toGroupGuid\030\004 \001(\t\022\023\n\013contentType\030\005" +
      " \001(\r\022\017\n\007content\030\006 \001(\t\022\023\n\013originalUrl\030\007 \001" +
      "(\t\022\022\n\npreviewUrl\030\010 \001(\t\022\022\n\nimageWidth\030\t \001" +
      "(\r\022\023\n\013imageHeight\030\n \001(\r\022\014\n\004size\030\013 \001(\r\022\020\n" +
      "\010playTime\030\014 \001(\r\022\020\n\010isFriend\030\r \001(\010\"D\n\031ImH" +
      "eartBeatMessageRequest\022\022\n\nfromUserId\030\001 \001" +
      "(\004\022\023\n\013currentTime\030\002 \001(\004\"X\n\031ImAddFriendMe" +
      "ssageRequest\022;\n\027addFriendMessageContent\030" +
      "\001 \001(\0132\032.ImAddFriendMessageContent\"l\n\032ImA" +
      "ddFriendMessageResponse\022;\n\027addFriendMess" +
      "ageContent\030\001 \001(\0132\032.ImAddFriendMessageCon" +
      "tent\022\021\n\tbuildTime\030\002 \001(\004\"\203\001\n\031ImAddFriendM" +
      "essageContent\022\022\n\nfromUserId\030\001 \001(\004\022\024\n\014fro" +
      "mUserName\030\002 \001(\t\022\031\n\021fromUserHeadImage\030\003 \001" +
      "(\t\022\020\n\010toUserId\030\004 \001(\004\022\017\n\007content\030\006 \001(\t\"E\n" +
      "\036ImTestConnectionMessageRequest\022\022\n\nfromU" +
      "serId\030\001 \001(\004\022\017\n\007content\030\002 \001(\t\"D\n\037ImTestCo" +
      "nnectionMessageResponse\022\017\n\007content\030\001 \001(\t" +
      "\022\020\n\010sendTime\030\002 \001(\004\"<\n\023ImAckMessageReques" +
      "t\022\022\n\nfromUserId\030\001 \001(\004\022\021\n\tmessageid\030\002 \001(\t" +
      "\"^\n\033ImChatSettingMessageRequest\022?\n\031chatS" +
      "ettingMessageContent\030\001 \001(\0132\034.ImChatSetti" +
      "ngMessageContent\"r\n\034ImChatSettingMessage" +
      "Response\022?\n\031chatSettingMessageContent\030\001 " +
      "\001(\0132\034.ImChatSettingMessageContent\022\021\n\tbui" +
      "ldTime\030\002 \001(\004\"\244\001\n\033ImChatSettingMessageCon" +
      "tent\022\'\n\013settingType\030\001 \001(\0162\022.ImChatSettin" +
      "gType\022#\n\013settingUser\030\002 \001(\0132\016.ImUserConte" +
      "nt\022\021\n\tgroupGuid\030\003 \001(\t\022\021\n\tgroupNote\030\004 \001(\t" +
      "\022\021\n\tgroupName\030\005 \001(\t\"a\n\034ImGroupOperateMes" +
      "sageRequest\022A\n\032groupOperateMessageConten" +
      "t\030\001 \001(\0132\035.ImGroupOperateMessageContent\"u" +
      "\n\035ImGroupOperateMessageResponse\022A\n\032group" +
      "OperateMessageContent\030\001 \001(\0132\035.ImGroupOpe" +
      "rateMessageContent\022\021\n\tbuildTime\030\002 \001(\004\"\267\001" +
      "\n\034ImGroupOperateMessageContent\022(\n\013operat" +
      "eType\030\001 \001(\0162\023.ImGroupOperateType\022#\n\013oper" +
      "ateUser\030\002 \001(\0132\016.ImUserContent\022\021\n\tgroupGu" +
      "id\030\003 \001(\t\022\021\n\tgroupName\030\004 \001(\t\022\"\n\ngroupUser" +
      "s\030\005 \003(\0132\016.ImUserContent\"]\n\rImUserContent" +
      "\022\016\n\006userId\030\001 \001(\004\022\020\n\010userName\030\002 \001(\t\022\021\n\tus" +
      "erImage\030\003 \001(\t\022\027\n\017groupUserRemark\030\004 \001(\t\"p" +
      "\n!ImNearCircleOperateMessageRequest\022K\n\037n" +
      "earCircleOperateMessageContent\030\001 \001(\0132\".I" +
      "mNearCircleOperateMessageContent\"\204\001\n\"ImN" +
      "earCircleOperateMessageResponse\022K\n\037nearC" +
      "ircleOperateMessageContent\030\001 \001(\0132\".ImNea" +
      "rCircleOperateMessageContent\022\021\n\tbuildTim" +
      "e\030\002 \001(\004\"\365\001\n!ImNearCircleOperateMessageCo" +
      "ntent\022)\n\013operateType\030\001 \001(\0162\024.ImCircleOpe" +
      "rateType\022 \n\010postUser\030\002 \001(\0132\016.ImUserConte" +
      "nt\022\"\n\noriginUser\030\003 \001(\0132\016.ImUserContent\022!" +
      "\n\treplyUser\030\004 \001(\0132\016.ImUserContent\022\024\n\014nea" +
      "rCircleId\030\005 \001(\004\022\021\n\tcommentId\030\006 \001(\004\022\023\n\013co" +
      "mmentCont\030\007 \001(\t\"d\n\035ImCircleOperateMessag" +
      "eRequest\022C\n\033circleOperateMessageContent\030" +
      "\001 \001(\0132\036.ImCircleOperateMessageContent\"x\n" +
      "\036ImCircleOperateMessageResponse\022C\n\033circl" +
      "eOperateMessageContent\030\001 \001(\0132\036.ImCircleO" +
      "perateMessageContent\022\021\n\tbuildTime\030\002 \001(\004\"" +
      "\355\001\n\035ImCircleOperateMessageContent\022)\n\013ope" +
      "rateType\030\001 \001(\0162\024.ImCircleOperateType\022 \n\010" +
      "postUser\030\002 \001(\0132\016.ImUserContent\022\"\n\norigin" +
      "User\030\003 \001(\0132\016.ImUserContent\022!\n\treplyUser\030" +
      "\004 \001(\0132\016.ImUserContent\022\020\n\010circleId\030\005 \001(\004\022" +
      "\021\n\tcommentId\030\006 \001(\004\022\023\n\013commentCont\030\007 \001(\t*" +
      "\335\001\n\rImMessageType\022\010\n\004Base\020\000\022\020\n\014UserValid" +
      "ate\020\001\022\014\n\010ChatUser\020\002\022\r\n\tChatGroup\020\003\022\r\n\tHe" +
      "artBeat\020\004\022\r\n\tAddFriend\020\005\022\022\n\016TestConnecti" +
      "on\020\006\022\024\n\020ClientAckMessage\020\007\022\017\n\013ChatSettin" +
      "g\020\010\022\020\n\014GroupOperate\020\t\022\025\n\021NearCircleOpera" +
      "te\020\n\022\021\n\rCircleOperate\020\013*S\n\025ImMessageResp" +
      "onseCode\022\t\n\005Other\020\000\022\013\n\007Success\020d\022\013\n\006Fail" +
      "ed\020\310\001\022\025\n\020SessionidInvalid\020\311\001*I\n\027ImMessag" +
      "eSourcePosition\022\010\n\004None\020\000\022\014\n\010RealTime\020\001\022" +
      "\013\n\007Offline\020\002\022\t\n\005Retry\020\003*R\n\021ImChatSetting" +
      "Type\022\017\n\013SettingNone\020\000\022\r\n\tGroupNote\020\001\022\r\n\t" +
      "GroupName\020\002\022\016\n\nUserRemark\020\003*y\n\022ImGroupOp" +
      "erateType\022\024\n\020GroupOperateNone\020\000\022\017\n\013Creat" +
      "eGroup\020\001\022\r\n\tExitGroup\020\002\022\020\n\014DismissGroup\020" +
      "\003\022\013\n\007AddUser\020\004\022\016\n\nRemoveUser\020\005*q\n\023ImCirc" +
      "leOperateType\022\031\n\025NearCircleOperateNone\020\000" +
      "\022\013\n\007AddLike\020\001\022\016\n\nCancelLike\020\002\022\017\n\013PostCom" +
      "ment\020\003\022\021\n\rCancelComment\020\004B,\n\026com.hwl.imc" +
      "ore.improtoP\001\252\002\017IMCore.Protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ImMessageContext_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImMessageContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImMessageContext_descriptor,
        new java.lang.String[] { "Type", "Request", "Response", "Body", });
    internal_static_ImMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ImMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImMessageRequest_descriptor,
        new java.lang.String[] { "RequestHead", "UserValidateRequest", "ChatUserMessageRequest", "ChatGroupMessageRequest", "HeartBeatMessageRequest", "AddFriendMessageRequest", "TestConnectionMessageRequest", "AckMessageRequest", "ChatSettingMessageRequest", "GroupOperateMessageRequest", "NearCircleOperateMessageRequest", "CircleOperateMessageRequest", "RequestBody", });
    internal_static_ImMessageRequestHead_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ImMessageRequestHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImMessageRequestHead_descriptor,
        new java.lang.String[] { "Timestamp", "Client", "Sessionid", "Language", "Version", });
    internal_static_ImMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ImMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImMessageResponse_descriptor,
        new java.lang.String[] { "ResponseHead", "UserValidateResponse", "ChatUserMessageResponse", "ChatGroupMessageResponse", "AddFriendMessageResponse", "TestConnectionMessageResponse", "ChatSettingMessageResponse", "GroupOperateMessageResponse", "NearCircleOperateMessageResponse", "CircleOperateMessageResponse", "ResponseBody", });
    internal_static_ImMessageResponseHead_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ImMessageResponseHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImMessageResponseHead_descriptor,
        new java.lang.String[] { "Code", "Message", "Isack", "Messageid", "Source", });
    internal_static_ImUserValidateRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ImUserValidateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImUserValidateRequest_descriptor,
        new java.lang.String[] { "UserId", "Token", "Messageid", });
    internal_static_ImUserValidateResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_ImUserValidateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImUserValidateResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "Message", "IsOnline", "Sessionid", });
    internal_static_ImChatUserMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ImChatUserMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImChatUserMessageRequest_descriptor,
        new java.lang.String[] { "ChatUserMessageContent", });
    internal_static_ImChatUserMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ImChatUserMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImChatUserMessageResponse_descriptor,
        new java.lang.String[] { "ChatUserMessageContent", "BuildTime", });
    internal_static_ImChatUserMessageContent_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ImChatUserMessageContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImChatUserMessageContent_descriptor,
        new java.lang.String[] { "FromUserId", "FromUserName", "FromUserImage", "ToUserId", "ContentType", "Content", "OriginalUrl", "PreviewUrl", "ImageWidth", "ImageHeight", "Size", "PlayTime", "IsFriend", });
    internal_static_ImChatGroupMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ImChatGroupMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImChatGroupMessageRequest_descriptor,
        new java.lang.String[] { "ChatGroupMessageContent", });
    internal_static_ImChatGroupMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ImChatGroupMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImChatGroupMessageResponse_descriptor,
        new java.lang.String[] { "ChatGroupMessageContent", "BuildTime", });
    internal_static_ImChatGroupMessageContent_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ImChatGroupMessageContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImChatGroupMessageContent_descriptor,
        new java.lang.String[] { "FromUserId", "FromUserName", "FromUserImage", "ToGroupGuid", "ContentType", "Content", "OriginalUrl", "PreviewUrl", "ImageWidth", "ImageHeight", "Size", "PlayTime", "IsFriend", });
    internal_static_ImHeartBeatMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ImHeartBeatMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImHeartBeatMessageRequest_descriptor,
        new java.lang.String[] { "FromUserId", "CurrentTime", });
    internal_static_ImAddFriendMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_ImAddFriendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImAddFriendMessageRequest_descriptor,
        new java.lang.String[] { "AddFriendMessageContent", });
    internal_static_ImAddFriendMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_ImAddFriendMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImAddFriendMessageResponse_descriptor,
        new java.lang.String[] { "AddFriendMessageContent", "BuildTime", });
    internal_static_ImAddFriendMessageContent_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_ImAddFriendMessageContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImAddFriendMessageContent_descriptor,
        new java.lang.String[] { "FromUserId", "FromUserName", "FromUserHeadImage", "ToUserId", "Content", });
    internal_static_ImTestConnectionMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_ImTestConnectionMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImTestConnectionMessageRequest_descriptor,
        new java.lang.String[] { "FromUserId", "Content", });
    internal_static_ImTestConnectionMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_ImTestConnectionMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImTestConnectionMessageResponse_descriptor,
        new java.lang.String[] { "Content", "SendTime", });
    internal_static_ImAckMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_ImAckMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImAckMessageRequest_descriptor,
        new java.lang.String[] { "FromUserId", "Messageid", });
    internal_static_ImChatSettingMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_ImChatSettingMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImChatSettingMessageRequest_descriptor,
        new java.lang.String[] { "ChatSettingMessageContent", });
    internal_static_ImChatSettingMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_ImChatSettingMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImChatSettingMessageResponse_descriptor,
        new java.lang.String[] { "ChatSettingMessageContent", "BuildTime", });
    internal_static_ImChatSettingMessageContent_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_ImChatSettingMessageContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImChatSettingMessageContent_descriptor,
        new java.lang.String[] { "SettingType", "SettingUser", "GroupGuid", "GroupNote", "GroupName", });
    internal_static_ImGroupOperateMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_ImGroupOperateMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImGroupOperateMessageRequest_descriptor,
        new java.lang.String[] { "GroupOperateMessageContent", });
    internal_static_ImGroupOperateMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_ImGroupOperateMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImGroupOperateMessageResponse_descriptor,
        new java.lang.String[] { "GroupOperateMessageContent", "BuildTime", });
    internal_static_ImGroupOperateMessageContent_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_ImGroupOperateMessageContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImGroupOperateMessageContent_descriptor,
        new java.lang.String[] { "OperateType", "OperateUser", "GroupGuid", "GroupName", "GroupUsers", });
    internal_static_ImUserContent_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_ImUserContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImUserContent_descriptor,
        new java.lang.String[] { "UserId", "UserName", "UserImage", "GroupUserRemark", });
    internal_static_ImNearCircleOperateMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_ImNearCircleOperateMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImNearCircleOperateMessageRequest_descriptor,
        new java.lang.String[] { "NearCircleOperateMessageContent", });
    internal_static_ImNearCircleOperateMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_ImNearCircleOperateMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImNearCircleOperateMessageResponse_descriptor,
        new java.lang.String[] { "NearCircleOperateMessageContent", "BuildTime", });
    internal_static_ImNearCircleOperateMessageContent_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_ImNearCircleOperateMessageContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImNearCircleOperateMessageContent_descriptor,
        new java.lang.String[] { "OperateType", "PostUser", "OriginUser", "ReplyUser", "NearCircleId", "CommentId", "CommentCont", });
    internal_static_ImCircleOperateMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_ImCircleOperateMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImCircleOperateMessageRequest_descriptor,
        new java.lang.String[] { "CircleOperateMessageContent", });
    internal_static_ImCircleOperateMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_ImCircleOperateMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImCircleOperateMessageResponse_descriptor,
        new java.lang.String[] { "CircleOperateMessageContent", "BuildTime", });
    internal_static_ImCircleOperateMessageContent_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_ImCircleOperateMessageContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImCircleOperateMessageContent_descriptor,
        new java.lang.String[] { "OperateType", "PostUser", "OriginUser", "ReplyUser", "CircleId", "CommentId", "CommentCont", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
