// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

public interface ImMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ImMessageRequestHead requestHead = 1;</code>
   */
  boolean hasRequestHead();
  /**
   * <code>.ImMessageRequestHead requestHead = 1;</code>
   */
  com.hwl.imcore.improto.ImMessageRequestHead getRequestHead();
  /**
   * <code>.ImMessageRequestHead requestHead = 1;</code>
   */
  com.hwl.imcore.improto.ImMessageRequestHeadOrBuilder getRequestHeadOrBuilder();

  /**
   * <code>.ImUserValidateRequest userValidateRequest = 2;</code>
   */
  boolean hasUserValidateRequest();
  /**
   * <code>.ImUserValidateRequest userValidateRequest = 2;</code>
   */
  com.hwl.imcore.improto.ImUserValidateRequest getUserValidateRequest();
  /**
   * <code>.ImUserValidateRequest userValidateRequest = 2;</code>
   */
  com.hwl.imcore.improto.ImUserValidateRequestOrBuilder getUserValidateRequestOrBuilder();

  /**
   * <code>.ImChatUserMessageRequest chatUserMessageRequest = 3;</code>
   */
  boolean hasChatUserMessageRequest();
  /**
   * <code>.ImChatUserMessageRequest chatUserMessageRequest = 3;</code>
   */
  com.hwl.imcore.improto.ImChatUserMessageRequest getChatUserMessageRequest();
  /**
   * <code>.ImChatUserMessageRequest chatUserMessageRequest = 3;</code>
   */
  com.hwl.imcore.improto.ImChatUserMessageRequestOrBuilder getChatUserMessageRequestOrBuilder();

  /**
   * <code>.ImChatGroupMessageRequest chatGroupMessageRequest = 4;</code>
   */
  boolean hasChatGroupMessageRequest();
  /**
   * <code>.ImChatGroupMessageRequest chatGroupMessageRequest = 4;</code>
   */
  com.hwl.imcore.improto.ImChatGroupMessageRequest getChatGroupMessageRequest();
  /**
   * <code>.ImChatGroupMessageRequest chatGroupMessageRequest = 4;</code>
   */
  com.hwl.imcore.improto.ImChatGroupMessageRequestOrBuilder getChatGroupMessageRequestOrBuilder();

  /**
   * <code>.ImHeartBeatMessageRequest heartBeatMessageRequest = 5;</code>
   */
  boolean hasHeartBeatMessageRequest();
  /**
   * <code>.ImHeartBeatMessageRequest heartBeatMessageRequest = 5;</code>
   */
  com.hwl.imcore.improto.ImHeartBeatMessageRequest getHeartBeatMessageRequest();
  /**
   * <code>.ImHeartBeatMessageRequest heartBeatMessageRequest = 5;</code>
   */
  com.hwl.imcore.improto.ImHeartBeatMessageRequestOrBuilder getHeartBeatMessageRequestOrBuilder();

  /**
   * <code>.ImAddFriendMessageRequest addFriendMessageRequest = 6;</code>
   */
  boolean hasAddFriendMessageRequest();
  /**
   * <code>.ImAddFriendMessageRequest addFriendMessageRequest = 6;</code>
   */
  com.hwl.imcore.improto.ImAddFriendMessageRequest getAddFriendMessageRequest();
  /**
   * <code>.ImAddFriendMessageRequest addFriendMessageRequest = 6;</code>
   */
  com.hwl.imcore.improto.ImAddFriendMessageRequestOrBuilder getAddFriendMessageRequestOrBuilder();

  /**
   * <code>.ImTestConnectionMessageRequest testConnectionMessageRequest = 7;</code>
   */
  boolean hasTestConnectionMessageRequest();
  /**
   * <code>.ImTestConnectionMessageRequest testConnectionMessageRequest = 7;</code>
   */
  com.hwl.imcore.improto.ImTestConnectionMessageRequest getTestConnectionMessageRequest();
  /**
   * <code>.ImTestConnectionMessageRequest testConnectionMessageRequest = 7;</code>
   */
  com.hwl.imcore.improto.ImTestConnectionMessageRequestOrBuilder getTestConnectionMessageRequestOrBuilder();

  /**
   * <code>.ImAckMessageRequest ackMessageRequest = 8;</code>
   */
  boolean hasAckMessageRequest();
  /**
   * <code>.ImAckMessageRequest ackMessageRequest = 8;</code>
   */
  com.hwl.imcore.improto.ImAckMessageRequest getAckMessageRequest();
  /**
   * <code>.ImAckMessageRequest ackMessageRequest = 8;</code>
   */
  com.hwl.imcore.improto.ImAckMessageRequestOrBuilder getAckMessageRequestOrBuilder();

  /**
   * <code>.ImChatSettingMessageRequest chatSettingMessageRequest = 9;</code>
   */
  boolean hasChatSettingMessageRequest();
  /**
   * <code>.ImChatSettingMessageRequest chatSettingMessageRequest = 9;</code>
   */
  com.hwl.imcore.improto.ImChatSettingMessageRequest getChatSettingMessageRequest();
  /**
   * <code>.ImChatSettingMessageRequest chatSettingMessageRequest = 9;</code>
   */
  com.hwl.imcore.improto.ImChatSettingMessageRequestOrBuilder getChatSettingMessageRequestOrBuilder();

  /**
   * <code>.ImGroupOperateMessageRequest groupOperateMessageRequest = 10;</code>
   */
  boolean hasGroupOperateMessageRequest();
  /**
   * <code>.ImGroupOperateMessageRequest groupOperateMessageRequest = 10;</code>
   */
  com.hwl.imcore.improto.ImGroupOperateMessageRequest getGroupOperateMessageRequest();
  /**
   * <code>.ImGroupOperateMessageRequest groupOperateMessageRequest = 10;</code>
   */
  com.hwl.imcore.improto.ImGroupOperateMessageRequestOrBuilder getGroupOperateMessageRequestOrBuilder();

  /**
   * <code>.ImNearCircleOperateMessageRequest nearCircleOperateMessageRequest = 11;</code>
   */
  boolean hasNearCircleOperateMessageRequest();
  /**
   * <code>.ImNearCircleOperateMessageRequest nearCircleOperateMessageRequest = 11;</code>
   */
  com.hwl.imcore.improto.ImNearCircleOperateMessageRequest getNearCircleOperateMessageRequest();
  /**
   * <code>.ImNearCircleOperateMessageRequest nearCircleOperateMessageRequest = 11;</code>
   */
  com.hwl.imcore.improto.ImNearCircleOperateMessageRequestOrBuilder getNearCircleOperateMessageRequestOrBuilder();

  public com.hwl.imcore.improto.ImMessageRequest.RequestBodyCase getRequestBodyCase();
}
