// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

public interface ImMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ImMessageRequestHead requestHead = 1;</code>
   */
  boolean hasRequestHead();
  /**
   * <code>.ImMessageRequestHead requestHead = 1;</code>
   */
  com.hwl.imcore.improto.ImMessageRequestHead getRequestHead();
  /**
   * <code>.ImMessageRequestHead requestHead = 1;</code>
   */
  com.hwl.imcore.improto.ImMessageRequestHeadOrBuilder getRequestHeadOrBuilder();

  /**
   * <code>.ImUserValidateRequest userValidateRequest = 2;</code>
   */
  boolean hasUserValidateRequest();
  /**
   * <code>.ImUserValidateRequest userValidateRequest = 2;</code>
   */
  com.hwl.imcore.improto.ImUserValidateRequest getUserValidateRequest();
  /**
   * <code>.ImUserValidateRequest userValidateRequest = 2;</code>
   */
  com.hwl.imcore.improto.ImUserValidateRequestOrBuilder getUserValidateRequestOrBuilder();

  /**
   * <code>.ImChatUserMessageRequest chatUserMessageRequest = 3;</code>
   */
  boolean hasChatUserMessageRequest();
  /**
   * <code>.ImChatUserMessageRequest chatUserMessageRequest = 3;</code>
   */
  com.hwl.imcore.improto.ImChatUserMessageRequest getChatUserMessageRequest();
  /**
   * <code>.ImChatUserMessageRequest chatUserMessageRequest = 3;</code>
   */
  com.hwl.imcore.improto.ImChatUserMessageRequestOrBuilder getChatUserMessageRequestOrBuilder();

  /**
   * <code>.ImChatGroupMessageRequest chatGroupMessageRequest = 4;</code>
   */
  boolean hasChatGroupMessageRequest();
  /**
   * <code>.ImChatGroupMessageRequest chatGroupMessageRequest = 4;</code>
   */
  com.hwl.imcore.improto.ImChatGroupMessageRequest getChatGroupMessageRequest();
  /**
   * <code>.ImChatGroupMessageRequest chatGroupMessageRequest = 4;</code>
   */
  com.hwl.imcore.improto.ImChatGroupMessageRequestOrBuilder getChatGroupMessageRequestOrBuilder();

  /**
   * <code>.ImHeartBeatMessageRequest heartBeatMessageRequest = 5;</code>
   */
  boolean hasHeartBeatMessageRequest();
  /**
   * <code>.ImHeartBeatMessageRequest heartBeatMessageRequest = 5;</code>
   */
  com.hwl.imcore.improto.ImHeartBeatMessageRequest getHeartBeatMessageRequest();
  /**
   * <code>.ImHeartBeatMessageRequest heartBeatMessageRequest = 5;</code>
   */
  com.hwl.imcore.improto.ImHeartBeatMessageRequestOrBuilder getHeartBeatMessageRequestOrBuilder();

  /**
   * <code>.ImAddFriendMessageRequest addFriendMessageRequest = 6;</code>
   */
  boolean hasAddFriendMessageRequest();
  /**
   * <code>.ImAddFriendMessageRequest addFriendMessageRequest = 6;</code>
   */
  com.hwl.imcore.improto.ImAddFriendMessageRequest getAddFriendMessageRequest();
  /**
   * <code>.ImAddFriendMessageRequest addFriendMessageRequest = 6;</code>
   */
  com.hwl.imcore.improto.ImAddFriendMessageRequestOrBuilder getAddFriendMessageRequestOrBuilder();

  /**
   * <code>.ImConfirmFriendMessageRequest confirmFriendMessageRequest = 7;</code>
   */
  boolean hasConfirmFriendMessageRequest();
  /**
   * <code>.ImConfirmFriendMessageRequest confirmFriendMessageRequest = 7;</code>
   */
  com.hwl.imcore.improto.ImConfirmFriendMessageRequest getConfirmFriendMessageRequest();
  /**
   * <code>.ImConfirmFriendMessageRequest confirmFriendMessageRequest = 7;</code>
   */
  com.hwl.imcore.improto.ImConfirmFriendMessageRequestOrBuilder getConfirmFriendMessageRequestOrBuilder();

  public com.hwl.imcore.improto.ImMessageRequest.RequestBodyCase getRequestBodyCase();
}
