// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

public interface ImSystemMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImSystemMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 toUserId = 1;</code>
   */
  long getToUserId();

  /**
   * <code>string toGroupGuid = 2;</code>
   */
  java.lang.String getToGroupGuid();
  /**
   * <code>string toGroupGuid = 2;</code>
   */
  com.google.protobuf.ByteString
      getToGroupGuidBytes();

  /**
   * <code>.ImSystemMessageContent systemMessageContent = 3;</code>
   */
  boolean hasSystemMessageContent();
  /**
   * <code>.ImSystemMessageContent systemMessageContent = 3;</code>
   */
  com.hwl.imcore.improto.ImSystemMessageContent getSystemMessageContent();
  /**
   * <code>.ImSystemMessageContent systemMessageContent = 3;</code>
   */
  com.hwl.imcore.improto.ImSystemMessageContentOrBuilder getSystemMessageContentOrBuilder();
}
