// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

/**
 * <pre>
 *system message
 * </pre>
 *
 * Protobuf enum {@code ImSystemMessageType}
 */
public enum ImSystemMessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>AddNearGroup = 0;</code>
   */
  AddNearGroup(0),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>AddNearGroup = 0;</code>
   */
  public static final int AddNearGroup_VALUE = 0;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ImSystemMessageType valueOf(int value) {
    return forNumber(value);
  }

  public static ImSystemMessageType forNumber(int value) {
    switch (value) {
      case 0: return AddNearGroup;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ImSystemMessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ImSystemMessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ImSystemMessageType>() {
          public ImSystemMessageType findValueByNumber(int number) {
            return ImSystemMessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.hwl.imcore.improto.ImMessage.getDescriptor().getEnumTypes().get(6);
  }

  private static final ImSystemMessageType[] VALUES = values();

  public static ImSystemMessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ImSystemMessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ImSystemMessageType)
}

