// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

public interface ImTestConnectionMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImTestConnectionMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 fromUserId = 1;</code>
   */
  long getFromUserId();

  /**
   * <code>string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>uint64 sendTime = 3;</code>
   */
  long getSendTime();
}
