// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/imcore/protocol/im_message.proto

package com.hwl.imcore.improto;

public interface ImUserValidateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImUserValidateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isSuccess = 1;</code>
   */
  boolean getIsSuccess();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>bool isOnline = 3;</code>
   */
  boolean getIsOnline();

  /**
   * <code>string sessionid = 4;</code>
   */
  java.lang.String getSessionid();
  /**
   * <code>string sessionid = 4;</code>
   */
  com.google.protobuf.ByteString
      getSessionidBytes();
}
