// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/im/protocol/im_message.proto

package com.hwl.im.improto;

public interface ImMessageContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImMessageContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ImMessageType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>.ImMessageType type = 1;</code>
   */
  com.hwl.im.improto.ImMessageType getType();

  /**
   * <code>.ImMessageRequest request = 2;</code>
   */
  boolean hasRequest();
  /**
   * <code>.ImMessageRequest request = 2;</code>
   */
  com.hwl.im.improto.ImMessageRequest getRequest();
  /**
   * <code>.ImMessageRequest request = 2;</code>
   */
  com.hwl.im.improto.ImMessageRequestOrBuilder getRequestOrBuilder();

  /**
   * <code>.ImMessageResponse response = 3;</code>
   */
  boolean hasResponse();
  /**
   * <code>.ImMessageResponse response = 3;</code>
   */
  com.hwl.im.improto.ImMessageResponse getResponse();
  /**
   * <code>.ImMessageResponse response = 3;</code>
   */
  com.hwl.im.improto.ImMessageResponseOrBuilder getResponseOrBuilder();

  public com.hwl.im.improto.ImMessageContext.BodyCase getBodyCase();
}
