// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/im/protocol/im_message.proto

package com.hwl.im.improto;

public interface ImMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ImMessageResponseHead responseHead = 1;</code>
   */
  boolean hasResponseHead();
  /**
   * <code>.ImMessageResponseHead responseHead = 1;</code>
   */
  com.hwl.im.improto.ImMessageResponseHead getResponseHead();
  /**
   * <code>.ImMessageResponseHead responseHead = 1;</code>
   */
  com.hwl.im.improto.ImMessageResponseHeadOrBuilder getResponseHeadOrBuilder();

  /**
   * <code>.ImUserValidateResponse userValidateResponse = 2;</code>
   */
  boolean hasUserValidateResponse();
  /**
   * <code>.ImUserValidateResponse userValidateResponse = 2;</code>
   */
  com.hwl.im.improto.ImUserValidateResponse getUserValidateResponse();
  /**
   * <code>.ImUserValidateResponse userValidateResponse = 2;</code>
   */
  com.hwl.im.improto.ImUserValidateResponseOrBuilder getUserValidateResponseOrBuilder();

  /**
   * <code>.ImChatUserMessageResponse chatUserMessageResponse = 3;</code>
   */
  boolean hasChatUserMessageResponse();
  /**
   * <code>.ImChatUserMessageResponse chatUserMessageResponse = 3;</code>
   */
  com.hwl.im.improto.ImChatUserMessageResponse getChatUserMessageResponse();
  /**
   * <code>.ImChatUserMessageResponse chatUserMessageResponse = 3;</code>
   */
  com.hwl.im.improto.ImChatUserMessageResponseOrBuilder getChatUserMessageResponseOrBuilder();

  /**
   * <code>.ImChatGroupMessageResponse chatGroupMessageResponse = 4;</code>
   */
  boolean hasChatGroupMessageResponse();
  /**
   * <code>.ImChatGroupMessageResponse chatGroupMessageResponse = 4;</code>
   */
  com.hwl.im.improto.ImChatGroupMessageResponse getChatGroupMessageResponse();
  /**
   * <code>.ImChatGroupMessageResponse chatGroupMessageResponse = 4;</code>
   */
  com.hwl.im.improto.ImChatGroupMessageResponseOrBuilder getChatGroupMessageResponseOrBuilder();

  /**
   * <code>.ImAddFriendMessageResponse addFriendMessageResponse = 5;</code>
   */
  boolean hasAddFriendMessageResponse();
  /**
   * <code>.ImAddFriendMessageResponse addFriendMessageResponse = 5;</code>
   */
  com.hwl.im.improto.ImAddFriendMessageResponse getAddFriendMessageResponse();
  /**
   * <code>.ImAddFriendMessageResponse addFriendMessageResponse = 5;</code>
   */
  com.hwl.im.improto.ImAddFriendMessageResponseOrBuilder getAddFriendMessageResponseOrBuilder();

  public com.hwl.im.improto.ImMessageResponse.ResponseBodyCase getResponseBodyCase();
}
