// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/hwl/im/protocol/im_message.proto

package com.hwl.im.improto;

public interface ImMessageRequestHeadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImMessageRequestHead)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 timestamp = 1;</code>
   */
  long getTimestamp();

  /**
   * <code>string client = 2;</code>
   */
  java.lang.String getClient();
  /**
   * <code>string client = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientBytes();

  /**
   * <code>string sessionid = 3;</code>
   */
  java.lang.String getSessionid();
  /**
   * <code>string sessionid = 3;</code>
   */
  com.google.protobuf.ByteString
      getSessionidBytes();

  /**
   * <code>string language = 4;</code>
   */
  java.lang.String getLanguage();
  /**
   * <code>string language = 4;</code>
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <code>string version = 5;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 5;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();
}
